# Pre-commit git hooks, run locally before every commit
# Init with
# $ pip install -r requirements-dev.txt
# $ pre-commit install

repos:
-   repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
    - id: black
      language_version: python3
