from typing import List


def repos_data() -> List[dict]:
    return [
        {
            "id": 372810152,
            "node_id": "MDEwOlJlcG9zaXRvcnkzNzI4MTAxNTI=",
            "name": "kytos",
            "full_name": "kytos-ng/kytos",
            "private": False,
            "owner": {
                "login": "kytos-ng",
                "id": 85117179,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjg1MTE3MTc5",
                "avatar_url": "https://avatars.githubusercontent.com/u/85117179?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/kytos-ng",
                "html_url": "https://github.com/kytos-ng",
                "followers_url": "https://api.github.com/users/kytos-ng/followers",
                "following_url": "https://api.github.com/users/kytos-ng/following{/other_user}",
                "gists_url": "https://api.github.com/users/kytos-ng/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/kytos-ng/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/kytos-ng/subscriptions",
                "organizations_url": "https://api.github.com/users/kytos-ng/orgs",
                "repos_url": "https://api.github.com/users/kytos-ng/repos",
                "events_url": "https://api.github.com/users/kytos-ng/events{/privacy}",
                "received_events_url": "https://api.github.com/users/kytos-ng/received_events",
                "type": "Organization",
                "site_admin": False,
            },
            "html_url": "https://github.com/kytos-ng/kytos",
            "description": "Kytos SDN Platform is the fastest way to deploy an SDN Network. With this you can deploy a basic OpenFlow controller or your own controller. Kytos was designed to be easy to install, use, develop and share Network Apps (NApps). Kytos is incredibly powerful and easy, its modular design makes Kytos a lightweight SDN Platform.",
            "fork": True,
            "url": "https://api.github.com/repos/kytos-ng/kytos",
            "forks_url": "https://api.github.com/repos/kytos-ng/kytos/forks",
            "keys_url": "https://api.github.com/repos/kytos-ng/kytos/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/kytos-ng/kytos/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/kytos-ng/kytos/teams",
            "hooks_url": "https://api.github.com/repos/kytos-ng/kytos/hooks",
            "issue_events_url": "https://api.github.com/repos/kytos-ng/kytos/issues/events{/number}",
            "events_url": "https://api.github.com/repos/kytos-ng/kytos/events",
            "assignees_url": "https://api.github.com/repos/kytos-ng/kytos/assignees{/user}",
            "branches_url": "https://api.github.com/repos/kytos-ng/kytos/branches{/branch}",
            "tags_url": "https://api.github.com/repos/kytos-ng/kytos/tags",
            "blobs_url": "https://api.github.com/repos/kytos-ng/kytos/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/kytos-ng/kytos/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/kytos-ng/kytos/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/kytos-ng/kytos/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/kytos-ng/kytos/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/kytos-ng/kytos/languages",
            "stargazers_url": "https://api.github.com/repos/kytos-ng/kytos/stargazers",
            "contributors_url": "https://api.github.com/repos/kytos-ng/kytos/contributors",
            "subscribers_url": "https://api.github.com/repos/kytos-ng/kytos/subscribers",
            "subscription_url": "https://api.github.com/repos/kytos-ng/kytos/subscription",
            "commits_url": "https://api.github.com/repos/kytos-ng/kytos/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/kytos-ng/kytos/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/kytos-ng/kytos/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/kytos-ng/kytos/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/kytos-ng/kytos/contents/{+path}",
            "compare_url": "https://api.github.com/repos/kytos-ng/kytos/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/kytos-ng/kytos/merges",
            "archive_url": "https://api.github.com/repos/kytos-ng/kytos/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/kytos-ng/kytos/downloads",
            "issues_url": "https://api.github.com/repos/kytos-ng/kytos/issues{/number}",
            "pulls_url": "https://api.github.com/repos/kytos-ng/kytos/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/kytos-ng/kytos/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/kytos-ng/kytos/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/kytos-ng/kytos/labels{/name}",
            "releases_url": "https://api.github.com/repos/kytos-ng/kytos/releases{/id}",
            "deployments_url": "https://api.github.com/repos/kytos-ng/kytos/deployments",
            "created_at": "2021-06-01T11:46:21Z",
            "updated_at": "2021-12-23T01:54:10Z",
            "pushed_at": "2022-02-15T19:38:32Z",
            "git_url": "git://github.com/kytos-ng/kytos.git",
            "ssh_url": "git@github.com:kytos-ng/kytos.git",
            "clone_url": "https://github.com/kytos-ng/kytos.git",
            "svn_url": "https://github.com/kytos-ng/kytos",
            "homepage": "https://kytos.io/",
            "size": 10048,
            "stargazers_count": 2,
            "watchers_count": 2,
            "language": "Python",
            "has_issues": True,
            "has_projects": True,
            "has_downloads": True,
            "has_wiki": True,
            "has_pages": False,
            "forks_count": 3,
            "mirror_url": None,
            "archived": False,
            "disabled": False,
            "open_issues_count": 126,
            "license": {
                "key": "mit",
                "name": "MIT License",
                "spdx_id": "MIT",
                "url": "https://api.github.com/licenses/mit",
                "node_id": "MDc6TGljZW5zZTEz",
            },
            "allow_forking": True,
            "is_template": False,
            "topics": [],
            "visibility": "public",
            "forks": 3,
            "open_issues": 126,
            "watchers": 2,
            "default_branch": "master",
            "permissions": {
                "admin": True,
                "maintain": True,
                "push": True,
                "triage": True,
                "pull": True,
            },
        },
        {
            "id": 372818494,
            "node_id": "MDEwOlJlcG9zaXRvcnkzNzI4MTg0OTQ=",
            "name": "kytos-utils",
            "full_name": "kytos-ng/kytos-utils",
            "private": False,
            "owner": {
                "login": "kytos-ng",
                "id": 85117179,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjg1MTE3MTc5",
                "avatar_url": "https://avatars.githubusercontent.com/u/85117179?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/kytos-ng",
                "html_url": "https://github.com/kytos-ng",
                "followers_url": "https://api.github.com/users/kytos-ng/followers",
                "following_url": "https://api.github.com/users/kytos-ng/following{/other_user}",
                "gists_url": "https://api.github.com/users/kytos-ng/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/kytos-ng/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/kytos-ng/subscriptions",
                "organizations_url": "https://api.github.com/users/kytos-ng/orgs",
                "repos_url": "https://api.github.com/users/kytos-ng/repos",
                "events_url": "https://api.github.com/users/kytos-ng/events{/privacy}",
                "received_events_url": "https://api.github.com/users/kytos-ng/received_events",
                "type": "Organization",
                "site_admin": False,
            },
            "html_url": "https://github.com/kytos-ng/kytos-utils",
            "description": "Command line interface (cli) for Kytos SDN Platform",
            "fork": True,
            "url": "https://api.github.com/repos/kytos-ng/kytos-utils",
            "forks_url": "https://api.github.com/repos/kytos-ng/kytos-utils/forks",
            "keys_url": "https://api.github.com/repos/kytos-ng/kytos-utils/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/kytos-ng/kytos-utils/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/kytos-ng/kytos-utils/teams",
            "hooks_url": "https://api.github.com/repos/kytos-ng/kytos-utils/hooks",
            "issue_events_url": "https://api.github.com/repos/kytos-ng/kytos-utils/issues/events{/number}",
            "events_url": "https://api.github.com/repos/kytos-ng/kytos-utils/events",
            "assignees_url": "https://api.github.com/repos/kytos-ng/kytos-utils/assignees{/user}",
            "branches_url": "https://api.github.com/repos/kytos-ng/kytos-utils/branches{/branch}",
            "tags_url": "https://api.github.com/repos/kytos-ng/kytos-utils/tags",
            "blobs_url": "https://api.github.com/repos/kytos-ng/kytos-utils/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/kytos-ng/kytos-utils/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/kytos-ng/kytos-utils/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/kytos-ng/kytos-utils/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/kytos-ng/kytos-utils/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/kytos-ng/kytos-utils/languages",
            "stargazers_url": "https://api.github.com/repos/kytos-ng/kytos-utils/stargazers",
            "contributors_url": "https://api.github.com/repos/kytos-ng/kytos-utils/contributors",
            "subscribers_url": "https://api.github.com/repos/kytos-ng/kytos-utils/subscribers",
            "subscription_url": "https://api.github.com/repos/kytos-ng/kytos-utils/subscription",
            "commits_url": "https://api.github.com/repos/kytos-ng/kytos-utils/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/kytos-ng/kytos-utils/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/kytos-ng/kytos-utils/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/kytos-ng/kytos-utils/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/kytos-ng/kytos-utils/contents/{+path}",
            "compare_url": "https://api.github.com/repos/kytos-ng/kytos-utils/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/kytos-ng/kytos-utils/merges",
            "archive_url": "https://api.github.com/repos/kytos-ng/kytos-utils/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/kytos-ng/kytos-utils/downloads",
            "issues_url": "https://api.github.com/repos/kytos-ng/kytos-utils/issues{/number}",
            "pulls_url": "https://api.github.com/repos/kytos-ng/kytos-utils/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/kytos-ng/kytos-utils/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/kytos-ng/kytos-utils/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/kytos-ng/kytos-utils/labels{/name}",
            "releases_url": "https://api.github.com/repos/kytos-ng/kytos-utils/releases{/id}",
            "deployments_url": "https://api.github.com/repos/kytos-ng/kytos-utils/deployments",
            "created_at": "2021-06-01T12:16:14Z",
            "updated_at": "2022-01-11T20:18:05Z",
            "pushed_at": "2022-01-21T20:37:16Z",
            "git_url": "git://github.com/kytos-ng/kytos-utils.git",
            "ssh_url": "git@github.com:kytos-ng/kytos-utils.git",
            "clone_url": "https://github.com/kytos-ng/kytos-utils.git",
            "svn_url": "https://github.com/kytos-ng/kytos-utils",
            "homepage": "https://kytos.io/",
            "size": 638,
            "stargazers_count": 0,
            "watchers_count": 0,
            "language": "Python",
            "has_issues": True,
            "has_projects": True,
            "has_downloads": True,
            "has_wiki": True,
            "has_pages": False,
            "forks_count": 1,
            "mirror_url": None,
            "archived": False,
            "disabled": False,
            "open_issues_count": 18,
            "license": {
                "key": "mit",
                "name": "MIT License",
                "spdx_id": "MIT",
                "url": "https://api.github.com/licenses/mit",
                "node_id": "MDc6TGljZW5zZTEz",
            },
            "allow_forking": True,
            "is_template": False,
            "topics": [],
            "visibility": "public",
            "forks": 1,
            "open_issues": 18,
            "watchers": 0,
            "default_branch": "master",
            "permissions": {
                "admin": True,
                "maintain": True,
                "push": True,
                "triage": True,
                "pull": True,
            },
        },
    ]


def repo_labels_data() -> List[dict]:
    return [
        {
            "id": 3065718398,
            "node_id": "MDU6TGFiZWwzMDY1NzE4Mzk4",
            "url": "https://api.github.com/repos/kytos-ng/flow_manager/labels/blueprint",
            "name": "blueprint",
            "color": "6bffa1",
            "default": False,
            "description": None,
        },
        {
            "id": 3049218924,
            "node_id": "MDU6TGFiZWwzMDQ5MjE4OTI0",
            "url": "https://api.github.com/repos/kytos-ng/flow_manager/labels/bug",
            "name": "bug",
            "color": "d73a4a",
            "default": True,
            "description": "Something isn't working",
        },
        {
            "id": 3049218927,
            "node_id": "MDU6TGFiZWwzMDQ5MjE4OTI3",
            "url": "https://api.github.com/repos/kytos-ng/flow_manager/labels/documentation",
            "name": "documentation",
            "color": "0075ca",
            "default": True,
            "description": "Improvements or additions to documentation",
        },
    ]


def search_issues_data() -> dict:
    return {
        "total_count": 4,
        "incomplete_results": False,
        "items": [
            {
                "url": "https://api.github.com/repos/kytos-ng/flow_manager/issues/75",
                "repository_url": "https://api.github.com/repos/kytos-ng/flow_manager",
                "labels_url": "https://api.github.com/repos/kytos-ng/flow_manager/issues/75/labels{/name}",
                "comments_url": "https://api.github.com/repos/kytos-ng/flow_manager/issues/75/comments",
                "events_url": "https://api.github.com/repos/kytos-ng/flow_manager/issues/75/events",
                "html_url": "https://github.com/kytos-ng/flow_manager/issues/75",
                "id": 1145885355,
                "node_id": "I_kwDOFjjCjs5ETNKr",
                "number": 75,
                "title": "Migrate from storehouse to a NoSQL supported database",
                "user": {
                    "login": "viniarck",
                    "id": 1010796,
                    "node_id": "MDQ6VXNlcjEwMTA3OTY=",
                    "avatar_url": "https://avatars.githubusercontent.com/u/1010796?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/viniarck",
                    "html_url": "https://github.com/viniarck",
                    "followers_url": "https://api.github.com/users/viniarck/followers",
                    "following_url": "https://api.github.com/users/viniarck/following{/other_user}",
                    "gists_url": "https://api.github.com/users/viniarck/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/viniarck/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/viniarck/subscriptions",
                    "organizations_url": "https://api.github.com/users/viniarck/orgs",
                    "repos_url": "https://api.github.com/users/viniarck/repos",
                    "events_url": "https://api.github.com/users/viniarck/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/viniarck/received_events",
                    "type": "User",
                    "site_admin": False,
                },
                "labels": [
                    {
                        "id": 3847767122,
                        "node_id": "LA_kwDOFjjCjs7lWERS",
                        "url": "https://api.github.com/repos/kytos-ng/flow_manager/labels/2022.3",
                        "name": "2022.3",
                        "color": "ededed",
                        "default": False,
                        "description": "Kytos-ng 2022.3",
                    },
                    {
                        "id": 3855847040,
                        "node_id": "LA_kwDOFjjCjs7l046A",
                        "url": "https://api.github.com/repos/kytos-ng/flow_manager/labels/epic_nosql_db",
                        "name": "epic_nosql_db",
                        "color": "C5DEF5",
                        "default": False,
                        "description": "NoSQL Database",
                    },
                    {
                        "id": 3856886175,
                        "node_id": "LA_kwDOFjjCjs7l42mf",
                        "url": "https://api.github.com/repos/kytos-ng/flow_manager/labels/epic_nosql_db_napps",
                        "name": "epic_nosql_db_napps",
                        "color": "C5DEF5",
                        "default": False,
                        "description": "NoSQL Database NApps",
                    },
                ],
                "state": "open",
                "locked": False,
                "assignee": None,
                "assignees": [],
                "milestone": None,
                "comments": 0,
                "created_at": "2022-02-21T14:39:16Z",
                "updated_at": "2022-02-21T19:59:57Z",
                "closed_at": None,
                "author_association": "MEMBER",
                "active_lock_reason": None,
                "body": "This is for migration from the filesystem backend from storehouse and use a [NoSQL database that will be supported](https://github.com/kytos-ng/kytos/issues/171) with a client directly. \r\n\r\n- The existing storage data should be migrated\r\n- Make sure to review and create indexes as necessary",
                "reactions": {
                    "url": "https://api.github.com/repos/kytos-ng/flow_manager/issues/75/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0,
                },
                "timeline_url": "https://api.github.com/repos/kytos-ng/flow_manager/issues/75/timeline",
                "performed_via_github_app": None,
                "score": 1.0,
            },
            {
                "url": "https://api.github.com/repos/kytos-ng/topology/issues/68",
                "repository_url": "https://api.github.com/repos/kytos-ng/topology",
                "labels_url": "https://api.github.com/repos/kytos-ng/topology/issues/68/labels{/name}",
                "comments_url": "https://api.github.com/repos/kytos-ng/topology/issues/68/comments",
                "events_url": "https://api.github.com/repos/kytos-ng/topology/issues/68/events",
                "html_url": "https://github.com/kytos-ng/topology/issues/68",
                "id": 1145883889,
                "node_id": "I_kwDOFjjCp85ETMzx",
                "number": 68,
                "title": "Migrate from storehouse to a NoSQL supported database",
                "user": {
                    "login": "viniarck",
                    "id": 1010796,
                    "node_id": "MDQ6VXNlcjEwMTA3OTY=",
                    "avatar_url": "https://avatars.githubusercontent.com/u/1010796?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/viniarck",
                    "html_url": "https://github.com/viniarck",
                    "followers_url": "https://api.github.com/users/viniarck/followers",
                    "following_url": "https://api.github.com/users/viniarck/following{/other_user}",
                    "gists_url": "https://api.github.com/users/viniarck/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/viniarck/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/viniarck/subscriptions",
                    "organizations_url": "https://api.github.com/users/viniarck/orgs",
                    "repos_url": "https://api.github.com/users/viniarck/repos",
                    "events_url": "https://api.github.com/users/viniarck/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/viniarck/received_events",
                    "type": "User",
                    "site_admin": False,
                },
                "labels": [
                    {
                        "id": 3847058377,
                        "node_id": "LA_kwDOFjjCp87lTXPJ",
                        "url": "https://api.github.com/repos/kytos-ng/topology/labels/2022.2",
                        "name": "2022.2",
                        "color": "ededed",
                        "default": False,
                        "description": "Kytos-ng 2022.2",
                    },
                    {
                        "id": 3855847043,
                        "node_id": "LA_kwDOFjjCp87l046D",
                        "url": "https://api.github.com/repos/kytos-ng/topology/labels/epic_nosql_db",
                        "name": "epic_nosql_db",
                        "color": "C5DEF5",
                        "default": False,
                        "description": "NoSQL Database",
                    },
                    {
                        "id": 3856874829,
                        "node_id": "LA_kwDOFjjCp87l4z1N",
                        "url": "https://api.github.com/repos/kytos-ng/topology/labels/epic_nosql_db_foundation",
                        "name": "epic_nosql_db_foundation",
                        "color": "C5DEF5",
                        "default": False,
                        "description": "NoSQL Database Foundation",
                    },
                ],
                "state": "open",
                "locked": False,
                "assignee": None,
                "assignees": [],
                "milestone": None,
                "comments": 0,
                "created_at": "2022-02-21T14:37:54Z",
                "updated_at": "2022-02-21T19:55:51Z",
                "closed_at": None,
                "author_association": "MEMBER",
                "active_lock_reason": None,
                "body": "This is for migration from the filesystem backend from storehouse and use a [NoSQL database that will be supported](https://github.com/kytos-ng/kytos/issues/171) with a client directly. \r\n\r\n- The existing storage data should be migrated\r\n- Make sure to review and create indexes as necessary",
                "reactions": {
                    "url": "https://api.github.com/repos/kytos-ng/topology/issues/68/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0,
                },
                "timeline_url": "https://api.github.com/repos/kytos-ng/topology/issues/68/timeline",
                "performed_via_github_app": None,
                "score": 1.0,
            },
            {
                "url": "https://api.github.com/repos/kytos-ng/mef_eline/issues/151",
                "repository_url": "https://api.github.com/repos/kytos-ng/mef_eline",
                "labels_url": "https://api.github.com/repos/kytos-ng/mef_eline/issues/151/labels{/name}",
                "comments_url": "https://api.github.com/repos/kytos-ng/mef_eline/issues/151/comments",
                "events_url": "https://api.github.com/repos/kytos-ng/mef_eline/issues/151/events",
                "html_url": "https://github.com/kytos-ng/mef_eline/issues/151",
                "id": 1145883109,
                "node_id": "I_kwDOFlnSic5ETMnl",
                "number": 151,
                "title": "Migrate from storehouse to a NoSQL supported database",
                "user": {
                    "login": "viniarck",
                    "id": 1010796,
                    "node_id": "MDQ6VXNlcjEwMTA3OTY=",
                    "avatar_url": "https://avatars.githubusercontent.com/u/1010796?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/viniarck",
                    "html_url": "https://github.com/viniarck",
                    "followers_url": "https://api.github.com/users/viniarck/followers",
                    "following_url": "https://api.github.com/users/viniarck/following{/other_user}",
                    "gists_url": "https://api.github.com/users/viniarck/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/viniarck/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/viniarck/subscriptions",
                    "organizations_url": "https://api.github.com/users/viniarck/orgs",
                    "repos_url": "https://api.github.com/users/viniarck/repos",
                    "events_url": "https://api.github.com/users/viniarck/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/viniarck/received_events",
                    "type": "User",
                    "site_admin": False,
                },
                "labels": [
                    {
                        "id": 3847767135,
                        "node_id": "LA_kwDOFlnSic7lWERf",
                        "url": "https://api.github.com/repos/kytos-ng/mef_eline/labels/2022.3",
                        "name": "2022.3",
                        "color": "ededed",
                        "default": False,
                        "description": "Kytos-ng 2022.3",
                    },
                    {
                        "id": 3855847045,
                        "node_id": "LA_kwDOFlnSic7l046F",
                        "url": "https://api.github.com/repos/kytos-ng/mef_eline/labels/epic_nosql_db",
                        "name": "epic_nosql_db",
                        "color": "C5DEF5",
                        "default": False,
                        "description": "NoSQL Database",
                    },
                    {
                        "id": 3856886177,
                        "node_id": "LA_kwDOFlnSic7l42mh",
                        "url": "https://api.github.com/repos/kytos-ng/mef_eline/labels/epic_nosql_db_napps",
                        "name": "epic_nosql_db_napps",
                        "color": "C5DEF5",
                        "default": False,
                        "description": "NoSQL Database NApps",
                    },
                ],
                "state": "open",
                "locked": False,
                "assignee": None,
                "assignees": [],
                "milestone": None,
                "comments": 0,
                "created_at": "2022-02-21T14:37:12Z",
                "updated_at": "2022-02-21T20:00:26Z",
                "closed_at": None,
                "author_association": "MEMBER",
                "active_lock_reason": None,
                "body": "This is for migration from the filesystem backend from storehouse and use a [NoSQL database that will be supported](https://github.com/kytos-ng/kytos/issues/171) with a client directly. \r\n\r\n- The existing storage data should be migrated\r\n- Make sure to review and create indexes as necessary",
                "reactions": {
                    "url": "https://api.github.com/repos/kytos-ng/mef_eline/issues/151/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0,
                },
                "timeline_url": "https://api.github.com/repos/kytos-ng/mef_eline/issues/151/timeline",
                "performed_via_github_app": None,
                "score": 1.0,
            },
            {
                "url": "https://api.github.com/repos/kytos-ng/kytos/issues/171",
                "repository_url": "https://api.github.com/repos/kytos-ng/kytos",
                "labels_url": "https://api.github.com/repos/kytos-ng/kytos/issues/171/labels{/name}",
                "comments_url": "https://api.github.com/repos/kytos-ng/kytos/issues/171/comments",
                "events_url": "https://api.github.com/repos/kytos-ng/kytos/issues/171/events",
                "html_url": "https://github.com/kytos-ng/kytos/issues/171",
                "id": 1145876415,
                "node_id": "I_kwDOFjihqM5ETK-_",
                "number": 171,
                "title": "Document basic requirements for the NoSQL supported database for general storage",
                "user": {
                    "login": "viniarck",
                    "id": 1010796,
                    "node_id": "MDQ6VXNlcjEwMTA3OTY=",
                    "avatar_url": "https://avatars.githubusercontent.com/u/1010796?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/viniarck",
                    "html_url": "https://github.com/viniarck",
                    "followers_url": "https://api.github.com/users/viniarck/followers",
                    "following_url": "https://api.github.com/users/viniarck/following{/other_user}",
                    "gists_url": "https://api.github.com/users/viniarck/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/viniarck/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/viniarck/subscriptions",
                    "organizations_url": "https://api.github.com/users/viniarck/orgs",
                    "repos_url": "https://api.github.com/users/viniarck/repos",
                    "events_url": "https://api.github.com/users/viniarck/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/viniarck/received_events",
                    "type": "User",
                    "site_admin": False,
                },
                "labels": [
                    {
                        "id": 3847058360,
                        "node_id": "LA_kwDOFjihqM7lTXO4",
                        "url": "https://api.github.com/repos/kytos-ng/kytos/labels/2022.2",
                        "name": "2022.2",
                        "color": "ededed",
                        "default": False,
                        "description": "Kytos-ng 2022.2",
                    },
                    {
                        "id": 3855847042,
                        "node_id": "LA_kwDOFjihqM7l046C",
                        "url": "https://api.github.com/repos/kytos-ng/kytos/labels/epic_nosql_db",
                        "name": "epic_nosql_db",
                        "color": "C5DEF5",
                        "default": False,
                        "description": "NoSQL Database",
                    },
                    {
                        "id": 3856874826,
                        "node_id": "LA_kwDOFjihqM7l4z1K",
                        "url": "https://api.github.com/repos/kytos-ng/kytos/labels/epic_nosql_db_foundation",
                        "name": "epic_nosql_db_foundation",
                        "color": "C5DEF5",
                        "default": False,
                        "description": "NoSQL Database Foundation",
                    },
                ],
                "state": "open",
                "locked": False,
                "assignee": None,
                "assignees": [],
                "milestone": None,
                "comments": 0,
                "created_at": "2022-02-21T14:31:16Z",
                "updated_at": "2022-02-21T19:56:14Z",
                "closed_at": None,
                "author_association": "MEMBER",
                "active_lock_reason": None,
                "body": "This is for documenting basic requirements and features for the NoSQL candidate database for general storage that NApps will be encouraged to use instead of using `storehouse` and use a client directly. ",
                "reactions": {
                    "url": "https://api.github.com/repos/kytos-ng/kytos/issues/171/reactions",
                    "total_count": 0,
                    "+1": 0,
                    "-1": 0,
                    "laugh": 0,
                    "hooray": 0,
                    "confused": 0,
                    "heart": 0,
                    "rocket": 0,
                    "eyes": 0,
                },
                "timeline_url": "https://api.github.com/repos/kytos-ng/kytos/issues/171/timeline",
                "performed_via_github_app": None,
                "score": 1.0,
            },
        ],
    }


def repo_issue_data() -> dict:
    """repo isso data."""
    return {
        "id": 1,
        "node_id": "MDU6SXNzdWUx",
        "url": "https://api.github.com/repos/octocat/Hello-World/issues/1347",
        "repository_url": "https://api.github.com/repos/octocat/Hello-World",
        "labels_url": "https://api.github.com/repos/octocat/Hello-World/issues/1347/labels{/name}",
        "comments_url": "https://api.github.com/repos/octocat/Hello-World/issues/1347/comments",
        "events_url": "https://api.github.com/repos/octocat/Hello-World/issues/1347/events",
        "html_url": "https://github.com/octocat/Hello-World/issues/1347",
        "number": 1347,
        "state": "open",
        "title": "Found a bug",
        "body": "I'm having a problem with this.",
        "user": {
            "login": "octocat",
            "id": 1,
            "node_id": "MDQ6VXNlcjE=",
            "avatar_url": "https://github.com/images/error/octocat_happy.gif",
            "gravatar_id": "",
            "url": "https://api.github.com/users/octocat",
            "html_url": "https://github.com/octocat",
            "followers_url": "https://api.github.com/users/octocat/followers",
            "following_url": "https://api.github.com/users/octocat/following{/other_user}",
            "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
            "organizations_url": "https://api.github.com/users/octocat/orgs",
            "repos_url": "https://api.github.com/users/octocat/repos",
            "events_url": "https://api.github.com/users/octocat/events{/privacy}",
            "received_events_url": "https://api.github.com/users/octocat/received_events",
            "type": "User",
        },
        "labels": [
            {
                "id": 208045946,
                "node_id": "MDU6TGFiZWwyMDgwNDU5NDY=",
                "url": "https://api.github.com/repos/octocat/Hello-World/labels/bug",
                "name": "bug",
                "description": "Something isn't working",
                "color": "f29513",
            }
        ],
        "assignees": [
            {
                "login": "octocat",
                "id": 1,
                "node_id": "MDQ6VXNlcjE=",
                "avatar_url": "https://github.com/images/error/octocat_happy.gif",
                "gravatar_id": "",
                "url": "https://api.github.com/users/octocat",
                "html_url": "https://github.com/octocat",
                "followers_url": "https://api.github.com/users/octocat/followers",
                "following_url": "https://api.github.com/users/octocat/following{/other_user}",
                "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
                "organizations_url": "https://api.github.com/users/octocat/orgs",
                "repos_url": "https://api.github.com/users/octocat/repos",
                "events_url": "https://api.github.com/users/octocat/events{/privacy}",
                "received_events_url": "https://api.github.com/users/octocat/received_events",
                "type": "User",
            }
        ],
        "active_lock_reason": "too heated",
        "comments": 0,
        "closed_at": None,
        "created_at": "2011-04-22T13:33:48Z",
        "updated_at": "2011-04-22T13:33:48Z",
        "state_reason": "completed",
    }
