from typing import List


def repos_data() -> List[dict]:
    return [
        {
            "id": 372810152,
            "node_id": "MDEwOlJlcG9zaXRvcnkzNzI4MTAxNTI=",
            "name": "kytos",
            "full_name": "kytos-ng/kytos",
            "private": False,
            "owner": {
                "login": "kytos-ng",
                "id": 85117179,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjg1MTE3MTc5",
                "avatar_url": "https://avatars.githubusercontent.com/u/85117179?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/kytos-ng",
                "html_url": "https://github.com/kytos-ng",
                "followers_url": "https://api.github.com/users/kytos-ng/followers",
                "following_url": "https://api.github.com/users/kytos-ng/following{/other_user}",
                "gists_url": "https://api.github.com/users/kytos-ng/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/kytos-ng/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/kytos-ng/subscriptions",
                "organizations_url": "https://api.github.com/users/kytos-ng/orgs",
                "repos_url": "https://api.github.com/users/kytos-ng/repos",
                "events_url": "https://api.github.com/users/kytos-ng/events{/privacy}",
                "received_events_url": "https://api.github.com/users/kytos-ng/received_events",
                "type": "Organization",
                "site_admin": False,
            },
            "html_url": "https://github.com/kytos-ng/kytos",
            "description": "Kytos SDN Platform is the fastest way to deploy an SDN Network. With this you can deploy a basic OpenFlow controller or your own controller. Kytos was designed to be easy to install, use, develop and share Network Apps (NApps). Kytos is incredibly powerful and easy, its modular design makes Kytos a lightweight SDN Platform.",
            "fork": True,
            "url": "https://api.github.com/repos/kytos-ng/kytos",
            "forks_url": "https://api.github.com/repos/kytos-ng/kytos/forks",
            "keys_url": "https://api.github.com/repos/kytos-ng/kytos/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/kytos-ng/kytos/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/kytos-ng/kytos/teams",
            "hooks_url": "https://api.github.com/repos/kytos-ng/kytos/hooks",
            "issue_events_url": "https://api.github.com/repos/kytos-ng/kytos/issues/events{/number}",
            "events_url": "https://api.github.com/repos/kytos-ng/kytos/events",
            "assignees_url": "https://api.github.com/repos/kytos-ng/kytos/assignees{/user}",
            "branches_url": "https://api.github.com/repos/kytos-ng/kytos/branches{/branch}",
            "tags_url": "https://api.github.com/repos/kytos-ng/kytos/tags",
            "blobs_url": "https://api.github.com/repos/kytos-ng/kytos/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/kytos-ng/kytos/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/kytos-ng/kytos/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/kytos-ng/kytos/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/kytos-ng/kytos/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/kytos-ng/kytos/languages",
            "stargazers_url": "https://api.github.com/repos/kytos-ng/kytos/stargazers",
            "contributors_url": "https://api.github.com/repos/kytos-ng/kytos/contributors",
            "subscribers_url": "https://api.github.com/repos/kytos-ng/kytos/subscribers",
            "subscription_url": "https://api.github.com/repos/kytos-ng/kytos/subscription",
            "commits_url": "https://api.github.com/repos/kytos-ng/kytos/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/kytos-ng/kytos/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/kytos-ng/kytos/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/kytos-ng/kytos/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/kytos-ng/kytos/contents/{+path}",
            "compare_url": "https://api.github.com/repos/kytos-ng/kytos/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/kytos-ng/kytos/merges",
            "archive_url": "https://api.github.com/repos/kytos-ng/kytos/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/kytos-ng/kytos/downloads",
            "issues_url": "https://api.github.com/repos/kytos-ng/kytos/issues{/number}",
            "pulls_url": "https://api.github.com/repos/kytos-ng/kytos/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/kytos-ng/kytos/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/kytos-ng/kytos/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/kytos-ng/kytos/labels{/name}",
            "releases_url": "https://api.github.com/repos/kytos-ng/kytos/releases{/id}",
            "deployments_url": "https://api.github.com/repos/kytos-ng/kytos/deployments",
            "created_at": "2021-06-01T11:46:21Z",
            "updated_at": "2021-12-23T01:54:10Z",
            "pushed_at": "2022-02-15T19:38:32Z",
            "git_url": "git://github.com/kytos-ng/kytos.git",
            "ssh_url": "git@github.com:kytos-ng/kytos.git",
            "clone_url": "https://github.com/kytos-ng/kytos.git",
            "svn_url": "https://github.com/kytos-ng/kytos",
            "homepage": "https://kytos.io/",
            "size": 10048,
            "stargazers_count": 2,
            "watchers_count": 2,
            "language": "Python",
            "has_issues": True,
            "has_projects": True,
            "has_downloads": True,
            "has_wiki": True,
            "has_pages": False,
            "forks_count": 3,
            "mirror_url": None,
            "archived": False,
            "disabled": False,
            "open_issues_count": 126,
            "license": {
                "key": "mit",
                "name": "MIT License",
                "spdx_id": "MIT",
                "url": "https://api.github.com/licenses/mit",
                "node_id": "MDc6TGljZW5zZTEz",
            },
            "allow_forking": True,
            "is_template": False,
            "topics": [],
            "visibility": "public",
            "forks": 3,
            "open_issues": 126,
            "watchers": 2,
            "default_branch": "master",
            "permissions": {
                "admin": True,
                "maintain": True,
                "push": True,
                "triage": True,
                "pull": True,
            },
        }
    ]


def repo_labels_data() -> List[dict]:
    return [
        {
            "id": 3065718398,
            "node_id": "MDU6TGFiZWwzMDY1NzE4Mzk4",
            "url": "https://api.github.com/repos/kytos-ng/flow_manager/labels/blueprint",
            "name": "blueprint",
            "color": "6bffa1",
            "default": False,
            "description": None,
        },
        {
            "id": 3049218924,
            "node_id": "MDU6TGFiZWwzMDQ5MjE4OTI0",
            "url": "https://api.github.com/repos/kytos-ng/flow_manager/labels/bug",
            "name": "bug",
            "color": "d73a4a",
            "default": True,
            "description": "Something isn't working",
        },
        {
            "id": 3049218927,
            "node_id": "MDU6TGFiZWwzMDQ5MjE4OTI3",
            "url": "https://api.github.com/repos/kytos-ng/flow_manager/labels/documentation",
            "name": "documentation",
            "color": "0075ca",
            "default": True,
            "description": "Improvements or additions to documentation",
        },
    ]
